Fix after breaking changes in Solidity v0.5.0
ensdomains/solsha1 pull request #9
Opened 2018-12-10 22:22 UTC by 0xC0DE4C0FFEE

Fixed test and contract codes to reflect breaking changes 
Tested OK
```
.....
    ✓ sha1.sol against test vector 149 (3514ms)
    ✓ sha1.sol against test vector 150 (3658ms)
    ✓ sha1.sol against test vector 151 (3850ms)
Base cost: 16722.857142857145 gas. Per 64 byte block: 22668.142857142855 gas
    ✓ benchmarks sha1 (562ms)

  153 passing (1m)
```

2018-12-11 05:23 UTC, Arachnid commented
Can you please change the pragmas so they work with both 0.4.x and 0.5? Otherwise this will break for existing users.

2018-12-11 09:29 UTC, Arachnid approved these changes

2018-12-11 09:30 UTC, Arachnid requested changes
It looks like you need >=, not >.

2018-12-11 12:00 UTC, 0xC0DE4C0FFEE commented
It actually works with solidity >0.4.18.
Changing to >0.4.24 so people will update their solc to latest version (0.4.25/0.5.0)

2018-12-12 22:02 UTC, Arachnid approved these changes

2018-12-12 22:02 UTC, merged